import { createHash } from "node:crypto";
export type ObservationKind="entity"|"state"|"signal"|"opportunity"|"problem"|"decision_subject";
export type SourceKind="browser"|"system"|"provider"|"user"|"sensor"|"derived";
export interface ObservationRule { rule_id:string; kind:ObservationKind; subject_type?:string; when_field:string; operator?:"exists"|"truthy"|"eq"|"gt"|"gte"|"lt"|"lte"; threshold?:unknown; label_template?:string; decision_question?:string; candidate_dimensions?:string[]; urgency?:string; base_confidence?:number; }
const forbidden=new Set(["tenant_id","tenant_company_id"]); const kinds=new Set(["entity","state","signal","opportunity","problem","decision_subject"]); const sources=new Set(["browser","system","provider","user","sensor","derived"]);
const now=()=>new Date().toISOString(); const stable=(prefix:string,v:unknown)=>prefix+"_"+createHash("sha256").update(JSON.stringify(v,Object.keys(v as any||{}).sort())).digest("hex").slice(0,20);
function assertBoundary(v:unknown,path="root"){ if(Array.isArray(v)) v.forEach((x,i)=>assertBoundary(x,`${path}[${i}]`)); else if(v&&typeof v==="object") for(const [k,x] of Object.entries(v as Record<string,unknown>)){ if(forbidden.has(k)) throw new Error(`legacy tenant boundary field rejected: ${path}.${k}`); assertBoundary(x,`${path}.${k}`); } }
function match(rule:ObservationRule,facts:Record<string,any>){ if(!(rule.when_field in facts)) return false; const v=facts[rule.when_field],op=rule.operator??"exists"; if(op==="exists") return v!==null&&v!==undefined; if(op==="truthy") return !!v; if(op==="eq") return v===rule.threshold; const n=Number(v),t=Number(rule.threshold??0); if(!Number.isFinite(n)) return false; return op==="gt"?n>t:op==="gte"?n>=t:op==="lt"?n<t:op==="lte"?n<=t:false; }
export class ObservationEngine {
 constructor(public rules:ObservationRule[]=[]){ }
 observeBrowser(company_id:string,url:string,title="",text="",structured:Record<string,any>={},metadata:Record<string,any>={}){ return this.observe({company_id,source_kind:"browser",source_id:url,url,title,text,structured,metadata}); }
 observeSystem(company_id:string,system_id:string,record_type:string,record_id:string,fields:Record<string,any>,provider_revision?:string){ return this.observe({company_id,source_kind:"system",source_id:system_id,record_type,record_id,fields,provider_revision}); }
 observe(context:Record<string,any>){ assertBoundary(context); if(!context.company_id) throw new Error("company_id required"); if(!sources.has(context.source_kind)) throw new Error("unsupported source_kind"); const facts=this.extractFacts(context); const subject_type=context.record_type??facts.entity_type??(context.source_kind==="browser"?"web_context":"context_entity"); const subject_key=String(context.record_id??facts.entity_id??context.source_id); const out:any[]=[]; out.push(this.emit(context.company_id,"entity",subject_type,subject_key,context,facts,`${subject_type}: ${facts.name??facts.title??subject_key}`,context.source_kind==="system"?.86:.68)); for(const r of this.rules) if(match(r,facts)) out.push(this.emit(context.company_id,r.kind,r.subject_type??subject_type,subject_key,context,facts,(r.label_template??"{subject_type}: {subject_key}").replace("{subject_type}",r.subject_type??subject_type).replace("{subject_key}",subject_key),r.base_confidence??.75,r.decision_question,r.candidate_dimensions??[],r.urgency??"none",[r.when_field],r.rule_id)); out.push(...this.generic(context.company_id,subject_type,subject_key,context,facts)); const seen=new Set<string>(); return out.filter(x=>!seen.has(x.observation_id)&&seen.add(x.observation_id)); }
 private extractFacts(c:Record<string,any>){ if(c.source_kind==="browser"){ const s={...(c.structured??{})}, text=String(c.text??"").slice(0,100000); const f:any={title:c.title??s.name,name:s.name,entity_type:s.entity_type??s["@type"],entity_id:s.id??s.sku,url:c.url,...s}; const pats:any={error_signal:/\b(error|failed|failure|problem)\b/i,deadline_signal:/\b(overdue|due today|deadline)\b/i,availability_signal:/\b(available|unavailable|out of stock|fully booked)\b/i,approval_signal:/\b(approval required|needs approval|awaiting approval)\b/i}; for(const [k,p] of Object.entries(pats)) f[k]=(p as RegExp).test(text); return f; } return { ...(c.fields??{}), entity_type:(c.fields??{}).entity_type??c.record_type, entity_id:(c.fields??{}).entity_id??c.record_id}; }
 private generic(cid:string,st:string,sk:string,c:Record<string,any>,f:Record<string,any>){ const out:any[]=[]; for(const key of ["status","state","stage","availability","condition"]) if(f[key]!=null) out.push(this.emit(cid,"state",st,sk,c,{[key]:f[key]},`${st} ${key}: ${f[key]}`,c.source_kind==="system"?.9:.7,undefined,[],"none",[key])); for(const key of ["error_signal","deadline_signal","availability_signal","approval_signal"]) if(f[key]) out.push(this.emit(cid,"signal",st,sk,c,{[key]:true},`Detected ${key.replaceAll("_"," ")}`,.58,undefined,[],"none",[key])); for(const [kind,fields] of [["problem",["problem","issue","risk_flag"]],["opportunity",["opportunity","improvement_opportunity","saving_opportunity"]]] as const){ const hit=fields.find(x=>f[x]); if(hit) out.push(this.emit(cid,kind,st,sk,c,{[hit]:f[hit]},`${kind[0].toUpperCase()+kind.slice(1)} candidate for ${st}`,c.source_kind==="system"?.75:.62,`What is the best response to this ${kind}?`,["risk","cost","time","impact"],"medium",[hit])); } if(f.decision_needed||f.requires_decision) out.push(this.emit(cid,"decision_subject",st,sk,c,{decision_needed:true},`Decision required for ${st}`,.85,`What is the best action for ${st} ${sk}?`,["cost","time","risk","quality","impact"],"medium",["decision_needed"])); return out; }
 private emit(cid:string,kind:string,st:string,sk:string,c:Record<string,any>,facts:Record<string,any>,label:string,confidence:number,question?:string,dimensions:string[]=[],urgency="none",supports:string[]=Object.keys(facts).slice(0,12),rule_id?:string){ if(!kinds.has(kind)) throw new Error("invalid kind"); const source={source_kind:c.source_kind,source_id:String(c.source_id??"unknown"),trust_class:c.source_kind==="system"?"authenticated":c.source_kind==="browser"?"untrusted":"contextual",url:c.url,provider_revision:c.provider_revision}; const evidence=supports.filter(k=>k in facts).map(k=>({evidence_id:stable("ev",{s:source.source_id,sk,k,v:facts[k]}),evidence_type:(c.fields??c.structured??{})[k]!==undefined?"raw":"derived",field:k,value:facts[k],unit:null,source_ref:source.source_id})); const base={company_id:cid,kind,subject:{type:st,key:sk},label,source,evidence,decision_context:question?{question,candidate_dimensions:dimensions,urgency}:null,confidence:{score:confidence,level:confidence>=.8?"high":confidence>=.5?"medium":"low"},observed_at:c.observed_at??now(),rule_id:rule_id??null,authority_effect:"none"}; return {observation_id:stable("obs",base),contract_version:"1.0.0",...base}; }
}
export const DEFAULT_RULES:ObservationRule[]=[]; export const defaultEngine=()=>new ObservationEngine(DEFAULT_RULES);
export class BrowserContextAdapter { constructor(private engine:ObservationEngine){} ingest(company_id:string,page:any){ return this.engine.observeBrowser(company_id,page.url,page.title??"",page.text??"",page.structured??{},page.metadata??{}); } }
export class SystemContextAdapter { constructor(private engine:ObservationEngine){} ingest(company_id:string,system_id:string,record_type:string,record_id:string,fields:any,provider_revision?:string){ return this.engine.observeSystem(company_id,system_id,record_type,record_id,fields,provider_revision); } }
