import { createHash } from "node:crypto";
export class RankingError extends Error {}
const now=()=>new Date().toISOString();
const id=(prefix:string,...parts:unknown[])=>`${prefix}_${createHash("sha256").update(parts.map(String).join("|")).digest("hex").slice(0,20)}`;
const clamp=(v:unknown)=>Math.max(0,Math.min(1,Number(v)));
const finite=(v:unknown)=>typeof v==="number" && Number.isFinite(v);

type Dimension={dimension_id:string;name:string;weight?:number;objective_refs?:string[]};
type Measurement={dimension_id:string;raw_value?:unknown;unit?:string;normalized_score?:number|null;confidence?:number;evidence_refs?:string[];assumptions?:string[]};
type Alternative={option_id:string;title?:string;eligible?:boolean;coverage?:number;measurements:Measurement[]};
type Comparison={comparison_id?:string;company_id:string;decision_subject_id:string;dimensions:Dimension[];alternatives:Alternative[]};
type Prediction={prediction_id?:string;option_id:string;outcome_key:string;confidence?:number;assumptions?:string[]};

function objectiveMultiplier(dim:Dimension, objectiveWeights:Record<string,number>):number { const vals=(dim.objective_refs??[]).flatMap(r=> r in objectiveWeights && finite(objectiveWeights[r]) && objectiveWeights[r]>=0 ? [objectiveWeights[r]]:[]); return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:1; }
function predictionAdjustment(optionId:string, dimensionName:string, pbo:Record<string,Prediction[]>) { const matches=(pbo[optionId]??[]).filter(p=>p.outcome_key===dimensionName); if(!matches.length)return{confidence_multiplier:1,assumptions:[] as string[],prediction_refs:[] as string[]}; const avg=matches.reduce((s,p)=>s+Math.max(0,Number(p.confidence??0)),0)/matches.length; return{confidence_multiplier:avg,assumptions:[...new Set(matches.flatMap(p=>p.assumptions??[]))],prediction_refs:matches.flatMap(p=>p.prediction_id?[p.prediction_id]:[])}; }
function scoreOnce(comparison:Comparison, objectiveWeights:Record<string,number>, overrides:Record<string,number>, pbo:Record<string,Prediction[]>) {
 const dims=Object.fromEntries(comparison.dimensions.map(d=>[d.dimension_id,d])); const scored:any[]=[]; const excluded:any[]=[];
 for(const a of comparison.alternatives){ if(a.eligible===false){excluded.push({option_id:a.option_id,reason:"hard_constraint_ineligible"});continue;} const ms=Object.fromEntries(a.measurements.map(m=>[m.dimension_id,m])); let numerator=0,denominator=0,confidenceNum=0; const factors:any[]=[]; const assumptions:string[]=[];
  for(const [did,d] of Object.entries(dims) as [string,Dimension][]){ const m:Measurement=ms[did]??{dimension_id:did}; const ns=m.normalized_score; const baseWeight=Number(d.weight??1); let effectiveWeight=Number(overrides[d.name]??overrides[did]??baseWeight)*objectiveMultiplier(d,objectiveWeights); if(effectiveWeight<0)throw new RankingError("negative_weight"); const pred=predictionAdjustment(a.option_id,d.name,pbo); const mconf=ns==null?0:clamp(m.confidence??0); const pconf=clamp(pred.confidence_multiplier); const combined=mconf*pconf; const contribution=ns==null?null:Number(ns)*effectiveWeight*combined; if(contribution!==null){numerator+=contribution;denominator+=effectiveWeight;confidenceNum+=effectiveWeight*combined;} const fa=[...new Set([...(m.assumptions??[]),...pred.assumptions])]; assumptions.push(...fa); factors.push({dimension_id:did,dimension:d.name,raw_value:m.raw_value,unit:m.unit,normalized_score:ns??null,base_weight:baseWeight,objective_multiplier:objectiveMultiplier(d,objectiveWeights),effective_weight:effectiveWeight,measurement_confidence:mconf,prediction_confidence_multiplier:pconf,combined_confidence:combined,weighted_contribution:contribution,evidence_refs:m.evidence_refs??[],prediction_refs:pred.prediction_refs,assumptions:fa}); }
  scored.push({option_id:a.option_id,title:a.title??a.option_id,score:+((denominator?numerator/denominator:0).toFixed(9)),rank_confidence:+((denominator?confidenceNum/denominator:0).toFixed(9)),comparison_coverage:a.coverage??0,factors,assumptions:[...new Set(assumptions)]}); }
 scored.sort((x,y)=>y.score-x.score||y.rank_confidence-x.rank_confidence||x.option_id.localeCompare(y.option_id)); let last:number|undefined,dense=0,rank=0; scored.forEach((row,i)=>{if(last===undefined||Math.abs(row.score-last)>1e-12){dense++;rank=i+1;}row.rank_position=rank;row.dense_rank=dense;last=row.score;}); return{scored,excluded};
}
export function rankAlternatives(companyId:string,decisionSubjectId:string,comparison:Comparison,opts:{objective_weights?:Record<string,number>;dimension_weight_overrides?:Record<string,number>;prediction_set?:{company_id:string;decision_subject_id:string;predictions?:Prediction[]};sensitivity_fraction?:number;created_at?:string;metadata?:Record<string,unknown>}={}){
 if(!companyId)throw new RankingError("company_id_required"); if(comparison.company_id!==companyId)throw new RankingError("cross_company_comparison"); if(comparison.decision_subject_id!==decisionSubjectId)throw new RankingError("decision_subject_mismatch"); const sf=opts.sensitivity_fraction??.25;if(sf<0||sf>1)throw new RankingError("bad_sensitivity_fraction"); const pbo:Record<string,Prediction[]>={}; if(opts.prediction_set){if(opts.prediction_set.company_id!==companyId)throw new RankingError("cross_company_prediction_set");if(opts.prediction_set.decision_subject_id!==decisionSubjectId)throw new RankingError("prediction_subject_mismatch");for(const p of opts.prediction_set.predictions??[])(pbo[p.option_id]??=[]).push(p);} const ow=opts.objective_weights??{}, ov=opts.dimension_weight_overrides??{}; const {scored:base,excluded}=scoreOnce(comparison,ow,ov,pbo); const baseOrder=base.map(x=>x.option_id),baseTop=baseOrder[0]??null; const scenarios:any[]=[];
 for(const d of comparison.dimensions){const w=Number(ov[d.name]??d.weight??1);for(const [change,factor] of [["decrease",1-sf],["increase",1+sf]] as const){const sov={...ov,[d.name]:Math.max(0,w*factor)};const {scored:rows}=scoreOnce(comparison,ow,sov,pbo);const order=rows.map(x=>x.option_id),top=order[0]??null;scenarios.push({scenario_id:id("sens",d.name,change,sov[d.name]),type:"dimension_weight",dimension:d.name,change,baseline_weight:w,scenario_weight:sov[d.name],top_option_id:top,top_changed:top!==baseTop,order_changed:JSON.stringify(order)!==JSON.stringify(baseOrder),order,scores:Object.fromEntries(rows.map(x=>[x.option_id,x.score]))});}}
 for(const oid of Object.keys(ow).sort()){const w0=ow[oid];if(!finite(w0)||w0<0)throw new RankingError("bad_objective_weight");for(const [change,factor] of [["decrease",1-sf],["increase",1+sf]] as const){const sow={...ow,[oid]:Math.max(0,w0*factor)};const {scored:rows}=scoreOnce(comparison,sow,ov,pbo);const order=rows.map(x=>x.option_id),top=order[0]??null;scenarios.push({scenario_id:id("sensobj",oid,change,sow[oid]),type:"objective_weight",objective_id:oid,change,baseline_weight:w0,scenario_weight:sow[oid],top_option_id:top,top_changed:top!==baseTop,order_changed:JSON.stringify(order)!==JSON.stringify(baseOrder),order,scores:Object.fromEntries(rows.map(x=>[x.option_id,x.score]))});}}
 const margin=base.length>1?base[0].score-base[1].score:base[0]?.score??0; return{ranking_id:id("rank",companyId,decisionSubjectId,comparison.comparison_id),contract_version:"1.0.0",company_id:companyId,decision_subject_id:decisionSubjectId,comparison_id:comparison.comparison_id??null,objective_weights:ow,dimension_weight_overrides:ov,ranked_alternatives:base,excluded_alternatives:excluded,leader_option_id:baseTop,leader_margin:+margin.toFixed(9),sensitivity:{fraction:sf,leader_is_sensitive:scenarios.some(s=>s.top_changed),scenarios},assumptions:[...new Set(base.flatMap(r=>r.assumptions))],authority_effect:"none" as const,created_at:opts.created_at??now(),metadata:opts.metadata??{}};
}
