import { createHash } from "node:crypto";
export class LearningLoopError extends Error {}
const clamp=(v:number)=>Math.max(0,Math.min(1,v)); const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex"); const id=(prefix:string,...p:unknown[])=>`${prefix}_${createHash("sha256").update(p.map(String).join("|")).digest("hex").slice(0,20)}`;
export type VerifiedOutcome={outcome_id:string;company_id:string;decision_subject_id:string;option_id:string;observed_at:string;verified:boolean;verification_refs:string[];metrics:Record<string,number>;success?:boolean;metadata?:Record<string,unknown>};
export type HistoricalDecision={company_id:string;decision_subject_id:string;decision_id:string;selected_option_id?:string|null;prediction_snapshot?:{predictions?:Array<{option_id:string;outcome_key:string;expected_value?:number;confidence?:number;assumptions?:string[]}>};ranking_snapshot?:{ranked_alternatives?:Array<{option_id:string;score:number;factors?:Array<{dimension:string;normalized_score?:number|null;effective_weight?:number;assumptions?:string[]}>}>};recommendation_snapshot?:{recommended_option_id?:string|null;confidence?:number};confidence_snapshot?:{raw_confidence?:number;calibrated_confidence?:number};evidence_refs?:string[];recorded_at:string};
export type LearningState={revision:number;forecast_stats:Record<string,{count:number;mae:number;bias:number}>;assumption_stats:Record<string,{count:number;successes:number;success_rate:number}>;recommendation_stats:{count:number;successes:number;success_rate:number};confidence_stats:{count:number;brier:number;mean_predicted:number;mean_observed:number};supersedes_learning_revision_id?:string|null};
export function learnFromVerifiedOutcome(companyId:string,historical:HistoricalDecision,outcome:VerifiedOutcome,prior?:LearningState){
 if(!companyId)throw new LearningLoopError("company_id_required"); if(historical.company_id!==companyId||outcome.company_id!==companyId)throw new LearningLoopError("cross_company_learning"); if(historical.decision_subject_id!==outcome.decision_subject_id)throw new LearningLoopError("decision_subject_mismatch"); if(!outcome.verified)throw new LearningLoopError("outcome_must_be_verified"); if(!outcome.verification_refs?.length)throw new LearningLoopError("verification_evidence_required");
 const historicalHash=hash(historical), outcomeHash=hash(outcome); const forecastStats=structuredClone(prior?.forecast_stats??{}); const assumptionStats=structuredClone(prior?.assumption_stats??{}); const rec=structuredClone(prior?.recommendation_stats??{count:0,successes:0,success_rate:0}); const conf=structuredClone(prior?.confidence_stats??{count:0,brier:0,mean_predicted:0,mean_observed:0}); const forecastObservations:any[]=[];
 for(const p of historical.prediction_snapshot?.predictions??[]){if(p.option_id!==outcome.option_id)continue;const actual=outcome.metrics[p.outcome_key];if(typeof actual!=="number"||typeof p.expected_value!=="number")continue;const err=actual-p.expected_value;const prev=forecastStats[p.outcome_key]??{count:0,mae:0,bias:0};const n=prev.count+1;forecastStats[p.outcome_key]={count:n,mae:((prev.mae*prev.count)+Math.abs(err))/n,bias:((prev.bias*prev.count)+err)/n};forecastObservations.push({outcome_key:p.outcome_key,expected:p.expected_value,actual,error:err,absolute_error:Math.abs(err),confidence:clamp(Number(p.confidence??0))}); for(const a of p.assumptions??[])updateAssumption(assumptionStats,a,outcome.success===true);}
 for(const r of historical.ranking_snapshot?.ranked_alternatives??[]){if(r.option_id!==outcome.option_id)continue;for(const f of r.factors??[])for(const a of f.assumptions??[])updateAssumption(assumptionStats,a,outcome.success===true);}
 const recommended=historical.recommendation_snapshot?.recommended_option_id??historical.selected_option_id??null; if(recommended!==null){rec.count++;if(recommended===outcome.option_id&&outcome.success===true)rec.successes++;rec.success_rate=rec.successes/rec.count;}
 const predicted=clamp(Number(historical.confidence_snapshot?.calibrated_confidence??historical.recommendation_snapshot?.confidence??0)); const observed=outcome.success===true?1:0; const cn=conf.count+1;conf.brier=((conf.brier*conf.count)+Math.pow(predicted-observed,2))/cn;conf.mean_predicted=((conf.mean_predicted*conf.count)+predicted)/cn;conf.mean_observed=((conf.mean_observed*conf.count)+observed)/cn;conf.count=cn;
 const revision=(prior?.revision??0)+1;const learningRevisionId=id("learnrev",companyId,historical.decision_id,outcome.outcome_id,revision,historicalHash,outcomeHash); const state:LearningState={revision,forecast_stats:forecastStats,assumption_stats:assumptionStats,recommendation_stats:rec,confidence_stats:conf,supersedes_learning_revision_id:prior? id("learnrev-prior",companyId,historical.decision_id,prior.revision):null};
 return {learning_event_id:id("learnevt",companyId,historical.decision_id,outcome.outcome_id),learning_revision_id:learningRevisionId,company_id:companyId,decision_subject_id:historical.decision_subject_id,decision_id:historical.decision_id,outcome_id:outcome.outcome_id,option_id:outcome.option_id,historical_snapshot_hash:historicalHash,outcome_snapshot_hash:outcomeHash,forecast_observations:forecastObservations,new_state:state,calibration_updates:{forecast:forecastStats,assumptions:assumptionStats,recommendations:rec,confidence:conf},historical_evidence_rewritten:false,historical_decision_rewritten:false,authority_effect:"none" as const,created_at:new Date().toISOString()};
}
function updateAssumption(stats:Record<string,{count:number;successes:number;success_rate:number}>,a:string,success:boolean){const p=stats[a]??{count:0,successes:0,success_rate:0};p.count++;if(success)p.successes++;p.success_rate=p.successes/p.count;stats[a]=p;}
export function applyLearningToFutureConfidence(raw:number,state:LearningState,minSamples=5){const c=state.confidence_stats;if(c.count<minSamples)return clamp(raw);const calibrationBias=c.mean_observed-c.mean_predicted;return clamp(raw+calibrationBias);}
export function assumptionReliability(assumption:string,state:LearningState){const s=state.assumption_stats[assumption];return s?{sample_count:s.count,reliability:s.success_rate}:{sample_count:0,reliability:null};}
