import { createHash } from "node:crypto";
export class ExplanationError extends Error {}
const ident=(p:string,...xs:unknown[])=>`${p}_${createHash("sha256").update(xs.map(String).join("|")).digest("hex").slice(0,20)}`;
const pct=(x:number)=>`${Math.round(x*100)}%`;
type Factor={dimension?:string;dimension_id?:string;raw_value?:unknown;unit?:string;normalized_score?:number|null;effective_weight?:number;combined_confidence?:number;weighted_contribution?:number|null;evidence_refs?:string[];prediction_refs?:string[];assumptions?:string[]};
type Ranked={option_id:string;title?:string;score:number;rank_position:number;rank_confidence?:number;comparison_coverage?:number;factors?:Factor[];assumptions?:string[]};
type Ranking={ranking_id:string;company_id:string;decision_subject_id:string;leader_option_id?:string|null;leader_margin?:number;ranked_alternatives:Ranked[];excluded_alternatives?:any[];sensitivity?:{leader_is_sensitive?:boolean;scenarios?:any[]};assumptions?:string[]};
type Best={decision_id:string;company_id:string;decision_subject_id:string;status:string;recommended_option_id?:string|null;leading_option_id?:string|null;reasons?:string[];authority_effect?:string};
function topFactors(r:Ranked,n=3){return [...(r.factors??[])].filter(f=>f.weighted_contribution!=null).sort((a,b)=>Number(b.weighted_contribution)-Number(a.weighted_contribution)).slice(0,n);}
function evidenceFrom(r:Ranked){return [...new Set((r.factors??[]).flatMap(f=>[...(f.evidence_refs??[]),...(f.prediction_refs??[])]))];}
function uncertainty(r:Ranked){const out:string[]=[];if((r.rank_confidence??0)<.75)out.push(`Ranking confidence is ${pct(r.rank_confidence??0)}.`);if((r.comparison_coverage??0)<.8)out.push(`Comparison coverage is ${pct(r.comparison_coverage??0)}.`);for(const a of r.assumptions??[])out.push(`Assumption: ${a}`);for(const f of r.factors??[])if((f.combined_confidence??1)<.6)out.push(`${f.dimension??f.dimension_id} has low confidence (${pct(f.combined_confidence??0)}).`);return [...new Set(out)];}
export function explainDecision(companyId:string,decisionSubjectId:string,ranking:Ranking,best:Best,opts:{created_at?:string;max_alternatives?:number}={}){
 if(!companyId)throw new ExplanationError("company_id_required");if(ranking.company_id!==companyId||best.company_id!==companyId)throw new ExplanationError("cross_company_input");if(ranking.decision_subject_id!==decisionSubjectId||best.decision_subject_id!==decisionSubjectId)throw new ExplanationError("decision_subject_mismatch");
 const leader=ranking.ranked_alternatives.find(x=>x.option_id===(best.recommended_option_id??best.leading_option_id??ranking.leader_option_id))??ranking.ranked_alternatives[0];
 if(!leader) return {explanation_id:ident("explain",companyId,decisionSubjectId,ranking.ranking_id),company_id:companyId,decision_subject_id:decisionSubjectId,status:"no_candidate",summary:"No eligible alternative was available to explain.",authority_effect:"none",created_at:opts.created_at??new Date().toISOString()};
 const strongest=topFactors(leader);const whyHigh=strongest.map(f=>`${f.dimension??f.dimension_id} contributed ${Number(f.weighted_contribution??0).toFixed(3)} at weight ${Number(f.effective_weight??0).toFixed(3)} and confidence ${pct(f.combined_confidence??0)}.`);
 const lower=ranking.ranked_alternatives.filter(x=>x.option_id!==leader.option_id).slice(0,opts.max_alternatives??4).map(a=>{const deltas:(string)[]=[];const lm=new Map((leader.factors??[]).map(f=>[f.dimension_id??f.dimension,f]));for(const f of a.factors??[]){const lf=lm.get(f.dimension_id??f.dimension);if(lf&&Number(lf.weighted_contribution??0)-Number(f.weighted_contribution??0)>.02)deltas.push(`${f.dimension??f.dimension_id} contributed less`);}return{option_id:a.option_id,title:a.title??a.option_id,rank_position:a.rank_position,score:a.score,score_gap:+(leader.score-a.score).toFixed(9),why_lower:deltas.slice(0,3)};});
 const evidence=evidenceFrom(leader);const uncertain=uncertainty(leader);const changes:any[]=[];
 for(const s of ranking.sensitivity?.scenarios??[]){if(s.top_changed)changes.push({type:s.type,dimension:s.dimension,objective_id:s.objective_id,change:s.change,scenario_weight:s.scenario_weight,new_top_option_id:s.top_option_id});}
 if(!changes.length&&ranking.sensitivity?.leader_is_sensitive)changes.push({type:"sensitivity",note:"The leader is marked sensitive, but no individual top-changing scenario was supplied."});
 const summary=best.status==="recommend"?`${leader.title??leader.option_id} ranks highest with score ${leader.score.toFixed(3)}. The recommendation is advisory and still requires normal Titan authority/governance before any action.`:`${leader.title??leader.option_id} is currently the leading alternative, but the engine abstained from a recommendation because ${[...(best.reasons??[])].join(", ")||"confidence or evidence was insufficient"}.`;
 return {explanation_id:ident("explain",companyId,decisionSubjectId,ranking.ranking_id,best.decision_id),contract_version:"1.0.0",company_id:companyId,decision_subject_id:decisionSubjectId,ranking_id:ranking.ranking_id,decision_id:best.decision_id,recommended_option_id:best.recommended_option_id??null,leading_option_id:leader.option_id,summary,why_highest:whyHigh,why_alternatives_ranked_lower:lower,evidence_that_mattered:evidence,uncertainties:uncertain,what_would_change_the_recommendation:changes,excluded_alternatives:ranking.excluded_alternatives??[],assumptions:[...new Set([...(ranking.assumptions??[]),...(leader.assumptions??[])])],explanation_basis:"structured_scores_evidence_assumptions_sensitivity_only",hidden_reasoning_included:false,authority_effect:"none" as const,created_at:opts.created_at??new Date().toISOString()};
}
