import assert from "node:assert/strict"; import { RankingError, rankAlternatives } from "../runtime/rankingEngine.js";
const cmp=()=>({comparison_id:"cmp1",company_id:"c1",decision_subject_id:"s1",dimensions:[{dimension_id:"dim_cost",name:"cost",weight:1,objective_refs:["obj_cost"]},{dimension_id:"dim_quality",name:"quality",weight:1,objective_refs:["obj_quality"]}],alternatives:[{option_id:"a",title:"A",eligible:true,coverage:1,measurements:[{dimension_id:"dim_cost",raw_value:10,unit:"AUD",normalized_score:1,confidence:.9,evidence_refs:["e1"],assumptions:[]},{dimension_id:"dim_quality",raw_value:6,normalized_score:.25,confidence:.8,evidence_refs:["e2"],assumptions:[]}]},{option_id:"b",title:"B",eligible:true,coverage:1,measurements:[{dimension_id:"dim_cost",raw_value:20,unit:"AUD",normalized_score:0,confidence:.9,evidence_refs:["e3"],assumptions:[]},{dimension_id:"dim_quality",raw_value:10,normalized_score:1,confidence:.9,evidence_refs:["e4"],assumptions:["quality holds"]}]},{option_id:"blocked",title:"Blocked",eligible:false,coverage:1,measurements:[{dimension_id:"dim_cost",raw_value:1,normalized_score:1,confidence:1},{dimension_id:"dim_quality",raw_value:10,normalized_score:1,confidence:1}]}]});
let r=rankAlternatives("c1","s1",cmp(),{objective_weights:{obj_cost:1,obj_quality:1}});assert.equal(r.ranked_alternatives[0].rank_position,1);assert.ok("weighted_contribution" in r.ranked_alternatives[0].factors[0]);assert.equal(r.excluded_alternatives[0].reason,"hard_constraint_ineligible");
const r1=rankAlternatives("c1","s1",cmp(),{objective_weights:{obj_cost:4,obj_quality:.2}}),r2=rankAlternatives("c1","s1",cmp(),{objective_weights:{obj_cost:.2,obj_quality:4}});assert.notEqual(r1.leader_option_id,r2.leader_option_id);
r=rankAlternatives("c1","s1",cmp(),{objective_weights:{obj_cost:1,obj_quality:1},sensitivity_fraction:.5});assert.ok(r.sensitivity.scenarios.length>=8);assert.ok("order_changed" in r.sensitivity.scenarios[0]);
r=rankAlternatives("c1","s1",cmp(),{prediction_set:{company_id:"c1",decision_subject_id:"s1",predictions:[{prediction_id:"p1",option_id:"b",outcome_key:"quality",confidence:.5,assumptions:["forecast uncertain"]}]}});const b=r.ranked_alternatives.find(x=>x.option_id==="b")!,q=b.factors.find((x:any)=>x.dimension==="quality");assert.equal(q.prediction_confidence_multiplier,.5);assert.ok(q.assumptions.includes("forecast uncertain"));
assert.throws(()=>rankAlternatives("c2","s1",cmp()),RankingError);assert.equal(rankAlternatives("c1","s1",cmp()).authority_effect,"none");assert.ok(!JSON.stringify(rankAlternatives("c1","s1",cmp())).includes("approval_granted"));
const c=cmp();c.alternatives=c.alternatives.slice(0,2);for(const a of c.alternatives)for(const m of a.measurements){m.normalized_score=.5;m.confidence=1;}r=rankAlternatives("c1","s1",c);assert.equal(r.ranked_alternatives[0].rank_position,1);assert.equal(r.ranked_alternatives[1].rank_position,1);
console.log("Step20 TypeScript tests: 8 passed");
